namespace WindowsFormsApp1
{
    partial class Main
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Main));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges9 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            this.bunifuPictureBox1 = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            this.panelContainer = new Bunifu.UI.WinForms.BunifuPanel();
            this.homeBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.EmployeeBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.salaryBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.AttendenceBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.branchBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.exitBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.reportBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.settingBtn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            this.pictureBox2 = new System.Windows.Forms.PictureBox();
            this.pictureBox3 = new System.Windows.Forms.PictureBox();
            this.pictureBox4 = new System.Windows.Forms.PictureBox();
            this.pictureBox5 = new System.Windows.Forms.PictureBox();
            this.pictureBox6 = new System.Windows.Forms.PictureBox();
            this.pictureBox7 = new System.Windows.Forms.PictureBox();
            this.pictureBox8 = new System.Windows.Forms.PictureBox();
            this.bunifuButton1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.pictureBox9 = new System.Windows.Forms.PictureBox();
            this.bunifuPanel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox3)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox4)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox5)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox6)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox7)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox8)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox9)).BeginInit();
            this.SuspendLayout();
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Georgia", 20.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel1.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel1.Location = new System.Drawing.Point(489, 29);
            this.bunifuLabel1.Margin = new System.Windows.Forms.Padding(4);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(330, 31);
            this.bunifuLabel1.TabIndex = 5;
            this.bunifuLabel1.Text = "Payroll Managment System";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuPanel1
            // 
            this.bunifuPanel1.BackgroundColor = System.Drawing.Color.DarkTurquoise;
            this.bunifuPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel1.BackgroundImage")));
            this.bunifuPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel1.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BorderRadius = 3;
            this.bunifuPanel1.BorderThickness = 1;
            this.bunifuPanel1.Controls.Add(this.bunifuPictureBox1);
            this.bunifuPanel1.Controls.Add(this.bunifuLabel3);
            this.bunifuPanel1.Controls.Add(this.bunifuLabel1);
            this.bunifuPanel1.Dock = System.Windows.Forms.DockStyle.Top;
            this.bunifuPanel1.Location = new System.Drawing.Point(0, 0);
            this.bunifuPanel1.Name = "bunifuPanel1";
            this.bunifuPanel1.ShowBorders = true;
            this.bunifuPanel1.Size = new System.Drawing.Size(1366, 99);
            this.bunifuPanel1.TabIndex = 7;
            // 
            // bunifuPictureBox1
            // 
            this.bunifuPictureBox1.AllowFocused = false;
            this.bunifuPictureBox1.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.bunifuPictureBox1.AutoSizeHeight = true;
            this.bunifuPictureBox1.BorderRadius = 24;
            this.bunifuPictureBox1.Image = ((System.Drawing.Image)(resources.GetObject("bunifuPictureBox1.Image")));
            this.bunifuPictureBox1.IsCircle = true;
            this.bunifuPictureBox1.Location = new System.Drawing.Point(1284, 29);
            this.bunifuPictureBox1.Name = "bunifuPictureBox1";
            this.bunifuPictureBox1.Size = new System.Drawing.Size(49, 49);
            this.bunifuPictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.bunifuPictureBox1.TabIndex = 0;
            this.bunifuPictureBox1.TabStop = false;
            this.bunifuPictureBox1.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Circle;
            this.bunifuPictureBox1.Click += new System.EventHandler(this.bunifuPictureBox1_Click);
            // 
            // bunifuLabel3
            // 
            this.bunifuLabel3.AllowParentOverrides = false;
            this.bunifuLabel3.AutoEllipsis = false;
            this.bunifuLabel3.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel3.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel3.Font = new System.Drawing.Font("Georgia", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel3.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel3.Location = new System.Drawing.Point(1155, 42);
            this.bunifuLabel3.Name = "bunifuLabel3";
            this.bunifuLabel3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel3.Size = new System.Drawing.Size(114, 18);
            this.bunifuLabel3.TabIndex = 8;
            this.bunifuLabel3.Text = "Nusra Mathloob";
            this.bunifuLabel3.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // panelContainer
            // 
            this.panelContainer.BackgroundColor = System.Drawing.Color.White;
            this.panelContainer.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("panelContainer.BackgroundImage")));
            this.panelContainer.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.panelContainer.BorderColor = System.Drawing.Color.Transparent;
            this.panelContainer.BorderRadius = 3;
            this.panelContainer.BorderThickness = 1;
            this.panelContainer.Location = new System.Drawing.Point(206, 97);
            this.panelContainer.Name = "panelContainer";
            this.panelContainer.ShowBorders = true;
            this.panelContainer.Size = new System.Drawing.Size(1200, 690);
            this.panelContainer.TabIndex = 9;
            // 
            // homeBtn
            // 
            this.homeBtn.AllowAnimations = true;
            this.homeBtn.AllowMouseEffects = true;
            this.homeBtn.AllowToggling = false;
            this.homeBtn.AnimationSpeed = 200;
            this.homeBtn.AutoGenerateColors = false;
            this.homeBtn.AutoRoundBorders = false;
            this.homeBtn.AutoSizeLeftIcon = true;
            this.homeBtn.AutoSizeRightIcon = true;
            this.homeBtn.BackColor = System.Drawing.Color.Transparent;
            this.homeBtn.BackColor1 = System.Drawing.Color.DarkTurquoise;
            this.homeBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("homeBtn.BackgroundImage")));
            this.homeBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.homeBtn.ButtonText = "Home";
            this.homeBtn.ButtonTextMarginLeft = 0;
            this.homeBtn.ColorContrastOnClick = 45;
            this.homeBtn.ColorContrastOnHover = 45;
            this.homeBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.homeBtn.CustomizableEdges = borderEdges1;
            this.homeBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.homeBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.homeBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.homeBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.homeBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.homeBtn.Font = new System.Drawing.Font("Georgia", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.homeBtn.ForeColor = System.Drawing.Color.White;
            this.homeBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.homeBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.homeBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.homeBtn.IconMarginLeft = 11;
            this.homeBtn.IconPadding = 10;
            this.homeBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.homeBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.homeBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.homeBtn.IconSize = 25;
            this.homeBtn.IdleBorderColor = System.Drawing.Color.DarkTurquoise;
            this.homeBtn.IdleBorderRadius = 1;
            this.homeBtn.IdleBorderThickness = 1;
            this.homeBtn.IdleFillColor = System.Drawing.Color.DarkTurquoise;
            this.homeBtn.IdleIconLeftImage = null;
            this.homeBtn.IdleIconRightImage = null;
            this.homeBtn.IndicateFocus = false;
            this.homeBtn.Location = new System.Drawing.Point(85, 234);
            this.homeBtn.Margin = new System.Windows.Forms.Padding(4);
            this.homeBtn.Name = "homeBtn";
            this.homeBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.homeBtn.OnDisabledState.BorderRadius = 1;
            this.homeBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.homeBtn.OnDisabledState.BorderThickness = 1;
            this.homeBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.homeBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.homeBtn.OnDisabledState.IconLeftImage = null;
            this.homeBtn.OnDisabledState.IconRightImage = null;
            this.homeBtn.onHoverState.BorderColor = System.Drawing.Color.DarkTurquoise;
            this.homeBtn.onHoverState.BorderRadius = 1;
            this.homeBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.homeBtn.onHoverState.BorderThickness = 1;
            this.homeBtn.onHoverState.FillColor = System.Drawing.Color.LightSeaGreen;
            this.homeBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.homeBtn.onHoverState.IconLeftImage = null;
            this.homeBtn.onHoverState.IconRightImage = null;
            this.homeBtn.OnIdleState.BorderColor = System.Drawing.Color.DarkTurquoise;
            this.homeBtn.OnIdleState.BorderRadius = 1;
            this.homeBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.homeBtn.OnIdleState.BorderThickness = 1;
            this.homeBtn.OnIdleState.FillColor = System.Drawing.Color.DarkTurquoise;
            this.homeBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.homeBtn.OnIdleState.IconLeftImage = null;
            this.homeBtn.OnIdleState.IconRightImage = null;
            this.homeBtn.OnPressedState.BorderColor = System.Drawing.Color.DarkTurquoise;
            this.homeBtn.OnPressedState.BorderRadius = 1;
            this.homeBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.homeBtn.OnPressedState.BorderThickness = 1;
            this.homeBtn.OnPressedState.FillColor = System.Drawing.Color.LightSeaGreen;
            this.homeBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.homeBtn.OnPressedState.IconLeftImage = null;
            this.homeBtn.OnPressedState.IconRightImage = null;
            this.homeBtn.Size = new System.Drawing.Size(114, 45);
            this.homeBtn.TabIndex = 0;
            this.homeBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.homeBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.homeBtn.TextMarginLeft = 0;
            this.homeBtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.homeBtn.UseDefaultRadiusAndThickness = true;
            this.homeBtn.Click += new System.EventHandler(this.homeBtn_Click);
            // 
            // EmployeeBtn
            // 
            this.EmployeeBtn.AllowAnimations = true;
            this.EmployeeBtn.AllowMouseEffects = true;
            this.EmployeeBtn.AllowToggling = false;
            this.EmployeeBtn.AnimationSpeed = 200;
            this.EmployeeBtn.AutoGenerateColors = false;
            this.EmployeeBtn.AutoRoundBorders = false;
            this.EmployeeBtn.AutoSizeLeftIcon = true;
            this.EmployeeBtn.AutoSizeRightIcon = true;
            this.EmployeeBtn.BackColor = System.Drawing.Color.Transparent;
            this.EmployeeBtn.BackColor1 = System.Drawing.Color.DarkTurquoise;
            this.EmployeeBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("EmployeeBtn.BackgroundImage")));
            this.EmployeeBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.EmployeeBtn.ButtonText = "Employee";
            this.EmployeeBtn.ButtonTextMarginLeft = 0;
            this.EmployeeBtn.ColorContrastOnClick = 45;
            this.EmployeeBtn.ColorContrastOnHover = 45;
            this.EmployeeBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.EmployeeBtn.CustomizableEdges = borderEdges2;
            this.EmployeeBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.EmployeeBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.EmployeeBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.EmployeeBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.EmployeeBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.EmployeeBtn.Font = new System.Drawing.Font("Georgia", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.EmployeeBtn.ForeColor = System.Drawing.Color.White;
            this.EmployeeBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.EmployeeBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.EmployeeBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.EmployeeBtn.IconMarginLeft = 11;
            this.EmployeeBtn.IconPadding = 10;
            this.EmployeeBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.EmployeeBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.EmployeeBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.EmployeeBtn.IconSize = 25;
            this.EmployeeBtn.IdleBorderColor = System.Drawing.Color.DarkTurquoise;
            this.EmployeeBtn.IdleBorderRadius = 1;
            this.EmployeeBtn.IdleBorderThickness = 1;
            this.EmployeeBtn.IdleFillColor = System.Drawing.Color.DarkTurquoise;
            this.EmployeeBtn.IdleIconLeftImage = null;
            this.EmployeeBtn.IdleIconRightImage = null;
            this.EmployeeBtn.IndicateFocus = false;
            this.EmployeeBtn.Location = new System.Drawing.Point(86, 299);
            this.EmployeeBtn.Margin = new System.Windows.Forms.Padding(4);
            this.EmployeeBtn.Name = "EmployeeBtn";
            this.EmployeeBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.EmployeeBtn.OnDisabledState.BorderRadius = 1;
            this.EmployeeBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.EmployeeBtn.OnDisabledState.BorderThickness = 1;
            this.EmployeeBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.EmployeeBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.EmployeeBtn.OnDisabledState.IconLeftImage = null;
            this.EmployeeBtn.OnDisabledState.IconRightImage = null;
            this.EmployeeBtn.onHoverState.BorderColor = System.Drawing.Color.DarkTurquoise;
            this.EmployeeBtn.onHoverState.BorderRadius = 1;
            this.EmployeeBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.EmployeeBtn.onHoverState.BorderThickness = 1;
            this.EmployeeBtn.onHoverState.FillColor = System.Drawing.Color.LightSeaGreen;
            this.EmployeeBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.EmployeeBtn.onHoverState.IconLeftImage = null;
            this.EmployeeBtn.onHoverState.IconRightImage = null;
            this.EmployeeBtn.OnIdleState.BorderColor = System.Drawing.Color.DarkTurquoise;
            this.EmployeeBtn.OnIdleState.BorderRadius = 1;
            this.EmployeeBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.EmployeeBtn.OnIdleState.BorderThickness = 1;
            this.EmployeeBtn.OnIdleState.FillColor = System.Drawing.Color.DarkTurquoise;
            this.EmployeeBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.EmployeeBtn.OnIdleState.IconLeftImage = null;
            this.EmployeeBtn.OnIdleState.IconRightImage = null;
            this.EmployeeBtn.OnPressedState.BorderColor = System.Drawing.Color.DarkTurquoise;
            this.EmployeeBtn.OnPressedState.BorderRadius = 1;
            this.EmployeeBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.EmployeeBtn.OnPressedState.BorderThickness = 1;
            this.EmployeeBtn.OnPressedState.FillColor = System.Drawing.Color.LightSeaGreen;
            this.EmployeeBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.EmployeeBtn.OnPressedState.IconLeftImage = null;
            this.EmployeeBtn.OnPressedState.IconRightImage = null;
            this.EmployeeBtn.Size = new System.Drawing.Size(114, 45);
            this.EmployeeBtn.TabIndex = 1;
            this.EmployeeBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.EmployeeBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.EmployeeBtn.TextMarginLeft = 0;
            this.EmployeeBtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.EmployeeBtn.UseDefaultRadiusAndThickness = true;
            this.EmployeeBtn.Click += new System.EventHandler(this.EmployeeBtn_Click);
            // 
            // salaryBtn
            // 
            this.salaryBtn.AllowAnimations = true;
            this.salaryBtn.AllowMouseEffects = true;
            this.salaryBtn.AllowToggling = false;
            this.salaryBtn.AnimationSpeed = 200;
            this.salaryBtn.AutoGenerateColors = false;
            this.salaryBtn.AutoRoundBorders = false;
            this.salaryBtn.AutoSizeLeftIcon = true;
            this.salaryBtn.AutoSizeRightIcon = true;
            this.salaryBtn.BackColor = System.Drawing.Color.Transparent;
            this.salaryBtn.BackColor1 = System.Drawing.Color.DarkTurquoise;
            this.salaryBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("salaryBtn.BackgroundImage")));
            this.salaryBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.salaryBtn.ButtonText = "Salary";
            this.salaryBtn.ButtonTextMarginLeft = 0;
            this.salaryBtn.ColorContrastOnClick = 45;
            this.salaryBtn.ColorContrastOnHover = 45;
            this.salaryBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.salaryBtn.CustomizableEdges = borderEdges3;
            this.salaryBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.salaryBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.salaryBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.salaryBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.salaryBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.salaryBtn.Font = new System.Drawing.Font("Georgia", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.salaryBtn.ForeColor = System.Drawing.Color.White;
            this.salaryBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.salaryBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.salaryBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.salaryBtn.IconMarginLeft = 11;
            this.salaryBtn.IconPadding = 10;
            this.salaryBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.salaryBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.salaryBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.salaryBtn.IconSize = 25;
            this.salaryBtn.IdleBorderColor = System.Drawing.Color.DarkTurquoise;
            this.salaryBtn.IdleBorderRadius = 1;
            this.salaryBtn.IdleBorderThickness = 1;
            this.salaryBtn.IdleFillColor = System.Drawing.Color.DarkTurquoise;
            this.salaryBtn.IdleIconLeftImage = null;
            this.salaryBtn.IdleIconRightImage = null;
            this.salaryBtn.IndicateFocus = false;
            this.salaryBtn.Location = new System.Drawing.Point(86, 357);
            this.salaryBtn.Margin = new System.Windows.Forms.Padding(4);
            this.salaryBtn.Name = "salaryBtn";
            this.salaryBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.salaryBtn.OnDisabledState.BorderRadius = 1;
            this.salaryBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.salaryBtn.OnDisabledState.BorderThickness = 1;
            this.salaryBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.salaryBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.salaryBtn.OnDisabledState.IconLeftImage = null;
            this.salaryBtn.OnDisabledState.IconRightImage = null;
            this.salaryBtn.onHoverState.BorderColor = System.Drawing.Color.DarkTurquoise;
            this.salaryBtn.onHoverState.BorderRadius = 1;
            this.salaryBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.salaryBtn.onHoverState.BorderThickness = 1;
            this.salaryBtn.onHoverState.FillColor = System.Drawing.Color.LightSeaGreen;
            this.salaryBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.salaryBtn.onHoverState.IconLeftImage = null;
            this.salaryBtn.onHoverState.IconRightImage = null;
            this.salaryBtn.OnIdleState.BorderColor = System.Drawing.Color.DarkTurquoise;
            this.salaryBtn.OnIdleState.BorderRadius = 1;
            this.salaryBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.salaryBtn.OnIdleState.BorderThickness = 1;
            this.salaryBtn.OnIdleState.FillColor = System.Drawing.Color.DarkTurquoise;
            this.salaryBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.salaryBtn.OnIdleState.IconLeftImage = null;
            this.salaryBtn.OnIdleState.IconRightImage = null;
            this.salaryBtn.OnPressedState.BorderColor = System.Drawing.Color.DarkTurquoise;
            this.salaryBtn.OnPressedState.BorderRadius = 1;
            this.salaryBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.salaryBtn.OnPressedState.BorderThickness = 1;
            this.salaryBtn.OnPressedState.FillColor = System.Drawing.Color.LightSeaGreen;
            this.salaryBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.salaryBtn.OnPressedState.IconLeftImage = null;
            this.salaryBtn.OnPressedState.IconRightImage = null;
            this.salaryBtn.Size = new System.Drawing.Size(114, 45);
            this.salaryBtn.TabIndex = 2;
            this.salaryBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.salaryBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.salaryBtn.TextMarginLeft = 0;
            this.salaryBtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.salaryBtn.UseDefaultRadiusAndThickness = true;
            this.salaryBtn.Click += new System.EventHandler(this.salaryBtn_Click);
            // 
            // AttendenceBtn
            // 
            this.AttendenceBtn.AllowAnimations = true;
            this.AttendenceBtn.AllowMouseEffects = true;
            this.AttendenceBtn.AllowToggling = false;
            this.AttendenceBtn.AnimationSpeed = 200;
            this.AttendenceBtn.AutoGenerateColors = false;
            this.AttendenceBtn.AutoRoundBorders = false;
            this.AttendenceBtn.AutoSizeLeftIcon = true;
            this.AttendenceBtn.AutoSizeRightIcon = true;
            this.AttendenceBtn.BackColor = System.Drawing.Color.Transparent;
            this.AttendenceBtn.BackColor1 = System.Drawing.Color.DarkTurquoise;
            this.AttendenceBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("AttendenceBtn.BackgroundImage")));
            this.AttendenceBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AttendenceBtn.ButtonText = "Attendence";
            this.AttendenceBtn.ButtonTextMarginLeft = 0;
            this.AttendenceBtn.ColorContrastOnClick = 45;
            this.AttendenceBtn.ColorContrastOnHover = 45;
            this.AttendenceBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.AttendenceBtn.CustomizableEdges = borderEdges4;
            this.AttendenceBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.AttendenceBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AttendenceBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AttendenceBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AttendenceBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.AttendenceBtn.Font = new System.Drawing.Font("Georgia", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.AttendenceBtn.ForeColor = System.Drawing.Color.White;
            this.AttendenceBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.AttendenceBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.AttendenceBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.AttendenceBtn.IconMarginLeft = 11;
            this.AttendenceBtn.IconPadding = 10;
            this.AttendenceBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.AttendenceBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.AttendenceBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.AttendenceBtn.IconSize = 25;
            this.AttendenceBtn.IdleBorderColor = System.Drawing.Color.DarkTurquoise;
            this.AttendenceBtn.IdleBorderRadius = 1;
            this.AttendenceBtn.IdleBorderThickness = 1;
            this.AttendenceBtn.IdleFillColor = System.Drawing.Color.DarkTurquoise;
            this.AttendenceBtn.IdleIconLeftImage = null;
            this.AttendenceBtn.IdleIconRightImage = null;
            this.AttendenceBtn.IndicateFocus = false;
            this.AttendenceBtn.Location = new System.Drawing.Point(86, 415);
            this.AttendenceBtn.Margin = new System.Windows.Forms.Padding(4);
            this.AttendenceBtn.Name = "AttendenceBtn";
            this.AttendenceBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.AttendenceBtn.OnDisabledState.BorderRadius = 1;
            this.AttendenceBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AttendenceBtn.OnDisabledState.BorderThickness = 1;
            this.AttendenceBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.AttendenceBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.AttendenceBtn.OnDisabledState.IconLeftImage = null;
            this.AttendenceBtn.OnDisabledState.IconRightImage = null;
            this.AttendenceBtn.onHoverState.BorderColor = System.Drawing.Color.DarkTurquoise;
            this.AttendenceBtn.onHoverState.BorderRadius = 1;
            this.AttendenceBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AttendenceBtn.onHoverState.BorderThickness = 1;
            this.AttendenceBtn.onHoverState.FillColor = System.Drawing.Color.LightSeaGreen;
            this.AttendenceBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.AttendenceBtn.onHoverState.IconLeftImage = null;
            this.AttendenceBtn.onHoverState.IconRightImage = null;
            this.AttendenceBtn.OnIdleState.BorderColor = System.Drawing.Color.DarkTurquoise;
            this.AttendenceBtn.OnIdleState.BorderRadius = 1;
            this.AttendenceBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AttendenceBtn.OnIdleState.BorderThickness = 1;
            this.AttendenceBtn.OnIdleState.FillColor = System.Drawing.Color.DarkTurquoise;
            this.AttendenceBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.AttendenceBtn.OnIdleState.IconLeftImage = null;
            this.AttendenceBtn.OnIdleState.IconRightImage = null;
            this.AttendenceBtn.OnPressedState.BorderColor = System.Drawing.Color.DarkTurquoise;
            this.AttendenceBtn.OnPressedState.BorderRadius = 1;
            this.AttendenceBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.AttendenceBtn.OnPressedState.BorderThickness = 1;
            this.AttendenceBtn.OnPressedState.FillColor = System.Drawing.Color.LightSeaGreen;
            this.AttendenceBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.AttendenceBtn.OnPressedState.IconLeftImage = null;
            this.AttendenceBtn.OnPressedState.IconRightImage = null;
            this.AttendenceBtn.Size = new System.Drawing.Size(114, 45);
            this.AttendenceBtn.TabIndex = 3;
            this.AttendenceBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.AttendenceBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.AttendenceBtn.TextMarginLeft = 0;
            this.AttendenceBtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.AttendenceBtn.UseDefaultRadiusAndThickness = true;
            // 
            // branchBtn
            // 
            this.branchBtn.AllowAnimations = true;
            this.branchBtn.AllowMouseEffects = true;
            this.branchBtn.AllowToggling = false;
            this.branchBtn.AnimationSpeed = 200;
            this.branchBtn.AutoGenerateColors = false;
            this.branchBtn.AutoRoundBorders = false;
            this.branchBtn.AutoSizeLeftIcon = true;
            this.branchBtn.AutoSizeRightIcon = true;
            this.branchBtn.BackColor = System.Drawing.Color.Transparent;
            this.branchBtn.BackColor1 = System.Drawing.Color.DarkTurquoise;
            this.branchBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("branchBtn.BackgroundImage")));
            this.branchBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.branchBtn.ButtonText = "Branch";
            this.branchBtn.ButtonTextMarginLeft = 0;
            this.branchBtn.ColorContrastOnClick = 45;
            this.branchBtn.ColorContrastOnHover = 45;
            this.branchBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.branchBtn.CustomizableEdges = borderEdges5;
            this.branchBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.branchBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.branchBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.branchBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.branchBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.branchBtn.Font = new System.Drawing.Font("Georgia", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.branchBtn.ForeColor = System.Drawing.Color.White;
            this.branchBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.branchBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.branchBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.branchBtn.IconMarginLeft = 11;
            this.branchBtn.IconPadding = 10;
            this.branchBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.branchBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.branchBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.branchBtn.IconSize = 25;
            this.branchBtn.IdleBorderColor = System.Drawing.Color.DarkTurquoise;
            this.branchBtn.IdleBorderRadius = 1;
            this.branchBtn.IdleBorderThickness = 1;
            this.branchBtn.IdleFillColor = System.Drawing.Color.DarkTurquoise;
            this.branchBtn.IdleIconLeftImage = null;
            this.branchBtn.IdleIconRightImage = null;
            this.branchBtn.IndicateFocus = false;
            this.branchBtn.Location = new System.Drawing.Point(85, 529);
            this.branchBtn.Margin = new System.Windows.Forms.Padding(4);
            this.branchBtn.Name = "branchBtn";
            this.branchBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.branchBtn.OnDisabledState.BorderRadius = 1;
            this.branchBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.branchBtn.OnDisabledState.BorderThickness = 1;
            this.branchBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.branchBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.branchBtn.OnDisabledState.IconLeftImage = null;
            this.branchBtn.OnDisabledState.IconRightImage = null;
            this.branchBtn.onHoverState.BorderColor = System.Drawing.Color.DarkTurquoise;
            this.branchBtn.onHoverState.BorderRadius = 1;
            this.branchBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.branchBtn.onHoverState.BorderThickness = 1;
            this.branchBtn.onHoverState.FillColor = System.Drawing.Color.LightSeaGreen;
            this.branchBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.branchBtn.onHoverState.IconLeftImage = null;
            this.branchBtn.onHoverState.IconRightImage = null;
            this.branchBtn.OnIdleState.BorderColor = System.Drawing.Color.DarkTurquoise;
            this.branchBtn.OnIdleState.BorderRadius = 1;
            this.branchBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.branchBtn.OnIdleState.BorderThickness = 1;
            this.branchBtn.OnIdleState.FillColor = System.Drawing.Color.DarkTurquoise;
            this.branchBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.branchBtn.OnIdleState.IconLeftImage = null;
            this.branchBtn.OnIdleState.IconRightImage = null;
            this.branchBtn.OnPressedState.BorderColor = System.Drawing.Color.DarkTurquoise;
            this.branchBtn.OnPressedState.BorderRadius = 1;
            this.branchBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.branchBtn.OnPressedState.BorderThickness = 1;
            this.branchBtn.OnPressedState.FillColor = System.Drawing.Color.LightSeaGreen;
            this.branchBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.branchBtn.OnPressedState.IconLeftImage = null;
            this.branchBtn.OnPressedState.IconRightImage = null;
            this.branchBtn.Size = new System.Drawing.Size(114, 45);
            this.branchBtn.TabIndex = 5;
            this.branchBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.branchBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.branchBtn.TextMarginLeft = 0;
            this.branchBtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.branchBtn.UseDefaultRadiusAndThickness = true;
            // 
            // exitBtn
            // 
            this.exitBtn.AllowAnimations = true;
            this.exitBtn.AllowMouseEffects = true;
            this.exitBtn.AllowToggling = false;
            this.exitBtn.AnimationSpeed = 200;
            this.exitBtn.AutoGenerateColors = false;
            this.exitBtn.AutoRoundBorders = false;
            this.exitBtn.AutoSizeLeftIcon = true;
            this.exitBtn.AutoSizeRightIcon = true;
            this.exitBtn.BackColor = System.Drawing.Color.Transparent;
            this.exitBtn.BackColor1 = System.Drawing.Color.Red;
            this.exitBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("exitBtn.BackgroundImage")));
            this.exitBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.exitBtn.ButtonText = "EXIT";
            this.exitBtn.ButtonTextMarginLeft = 0;
            this.exitBtn.ColorContrastOnClick = 45;
            this.exitBtn.ColorContrastOnHover = 45;
            this.exitBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.exitBtn.CustomizableEdges = borderEdges6;
            this.exitBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.exitBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.exitBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.exitBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.exitBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.exitBtn.Font = new System.Drawing.Font("Georgia", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.exitBtn.ForeColor = System.Drawing.Color.White;
            this.exitBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.exitBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.exitBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.exitBtn.IconMarginLeft = 11;
            this.exitBtn.IconPadding = 10;
            this.exitBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.exitBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.exitBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.exitBtn.IconSize = 25;
            this.exitBtn.IdleBorderColor = System.Drawing.Color.Red;
            this.exitBtn.IdleBorderRadius = 1;
            this.exitBtn.IdleBorderThickness = 1;
            this.exitBtn.IdleFillColor = System.Drawing.Color.Red;
            this.exitBtn.IdleIconLeftImage = null;
            this.exitBtn.IdleIconRightImage = null;
            this.exitBtn.IndicateFocus = false;
            this.exitBtn.Location = new System.Drawing.Point(84, 703);
            this.exitBtn.Margin = new System.Windows.Forms.Padding(4);
            this.exitBtn.Name = "exitBtn";
            this.exitBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.exitBtn.OnDisabledState.BorderRadius = 1;
            this.exitBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.exitBtn.OnDisabledState.BorderThickness = 1;
            this.exitBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.exitBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.exitBtn.OnDisabledState.IconLeftImage = null;
            this.exitBtn.OnDisabledState.IconRightImage = null;
            this.exitBtn.onHoverState.BorderColor = System.Drawing.Color.Red;
            this.exitBtn.onHoverState.BorderRadius = 1;
            this.exitBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.exitBtn.onHoverState.BorderThickness = 1;
            this.exitBtn.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.exitBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.exitBtn.onHoverState.IconLeftImage = null;
            this.exitBtn.onHoverState.IconRightImage = null;
            this.exitBtn.OnIdleState.BorderColor = System.Drawing.Color.Red;
            this.exitBtn.OnIdleState.BorderRadius = 1;
            this.exitBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.exitBtn.OnIdleState.BorderThickness = 1;
            this.exitBtn.OnIdleState.FillColor = System.Drawing.Color.Red;
            this.exitBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.exitBtn.OnIdleState.IconLeftImage = null;
            this.exitBtn.OnIdleState.IconRightImage = null;
            this.exitBtn.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.exitBtn.OnPressedState.BorderRadius = 1;
            this.exitBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.exitBtn.OnPressedState.BorderThickness = 1;
            this.exitBtn.OnPressedState.FillColor = System.Drawing.Color.Red;
            this.exitBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.exitBtn.OnPressedState.IconLeftImage = null;
            this.exitBtn.OnPressedState.IconRightImage = null;
            this.exitBtn.Size = new System.Drawing.Size(115, 45);
            this.exitBtn.TabIndex = 8;
            this.exitBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.exitBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.exitBtn.TextMarginLeft = 0;
            this.exitBtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.exitBtn.UseDefaultRadiusAndThickness = true;
            this.exitBtn.Click += new System.EventHandler(this.exitBtn_Click);
            // 
            // reportBtn
            // 
            this.reportBtn.AllowAnimations = true;
            this.reportBtn.AllowMouseEffects = true;
            this.reportBtn.AllowToggling = false;
            this.reportBtn.AnimationSpeed = 200;
            this.reportBtn.AutoGenerateColors = false;
            this.reportBtn.AutoRoundBorders = false;
            this.reportBtn.AutoSizeLeftIcon = true;
            this.reportBtn.AutoSizeRightIcon = true;
            this.reportBtn.BackColor = System.Drawing.Color.Transparent;
            this.reportBtn.BackColor1 = System.Drawing.Color.DarkTurquoise;
            this.reportBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("reportBtn.BackgroundImage")));
            this.reportBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.reportBtn.ButtonText = "Report";
            this.reportBtn.ButtonTextMarginLeft = 0;
            this.reportBtn.ColorContrastOnClick = 45;
            this.reportBtn.ColorContrastOnHover = 45;
            this.reportBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.reportBtn.CustomizableEdges = borderEdges7;
            this.reportBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.reportBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.reportBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.reportBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.reportBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.reportBtn.Font = new System.Drawing.Font("Georgia", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.reportBtn.ForeColor = System.Drawing.Color.White;
            this.reportBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.reportBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.reportBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.reportBtn.IconMarginLeft = 11;
            this.reportBtn.IconPadding = 10;
            this.reportBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.reportBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.reportBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.reportBtn.IconSize = 25;
            this.reportBtn.IdleBorderColor = System.Drawing.Color.DarkTurquoise;
            this.reportBtn.IdleBorderRadius = 1;
            this.reportBtn.IdleBorderThickness = 1;
            this.reportBtn.IdleFillColor = System.Drawing.Color.DarkTurquoise;
            this.reportBtn.IdleIconLeftImage = null;
            this.reportBtn.IdleIconRightImage = null;
            this.reportBtn.IndicateFocus = false;
            this.reportBtn.Location = new System.Drawing.Point(85, 587);
            this.reportBtn.Margin = new System.Windows.Forms.Padding(4);
            this.reportBtn.Name = "reportBtn";
            this.reportBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.reportBtn.OnDisabledState.BorderRadius = 1;
            this.reportBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.reportBtn.OnDisabledState.BorderThickness = 1;
            this.reportBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.reportBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.reportBtn.OnDisabledState.IconLeftImage = null;
            this.reportBtn.OnDisabledState.IconRightImage = null;
            this.reportBtn.onHoverState.BorderColor = System.Drawing.Color.DarkTurquoise;
            this.reportBtn.onHoverState.BorderRadius = 1;
            this.reportBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.reportBtn.onHoverState.BorderThickness = 1;
            this.reportBtn.onHoverState.FillColor = System.Drawing.Color.LightSeaGreen;
            this.reportBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.reportBtn.onHoverState.IconLeftImage = null;
            this.reportBtn.onHoverState.IconRightImage = null;
            this.reportBtn.OnIdleState.BorderColor = System.Drawing.Color.DarkTurquoise;
            this.reportBtn.OnIdleState.BorderRadius = 1;
            this.reportBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.reportBtn.OnIdleState.BorderThickness = 1;
            this.reportBtn.OnIdleState.FillColor = System.Drawing.Color.DarkTurquoise;
            this.reportBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.reportBtn.OnIdleState.IconLeftImage = null;
            this.reportBtn.OnIdleState.IconRightImage = null;
            this.reportBtn.OnPressedState.BorderColor = System.Drawing.Color.DarkTurquoise;
            this.reportBtn.OnPressedState.BorderRadius = 1;
            this.reportBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.reportBtn.OnPressedState.BorderThickness = 1;
            this.reportBtn.OnPressedState.FillColor = System.Drawing.Color.LightSeaGreen;
            this.reportBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.reportBtn.OnPressedState.IconLeftImage = null;
            this.reportBtn.OnPressedState.IconRightImage = null;
            this.reportBtn.Size = new System.Drawing.Size(114, 45);
            this.reportBtn.TabIndex = 6;
            this.reportBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.reportBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.reportBtn.TextMarginLeft = 0;
            this.reportBtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.reportBtn.UseDefaultRadiusAndThickness = true;
            // 
            // settingBtn
            // 
            this.settingBtn.AllowAnimations = true;
            this.settingBtn.AllowMouseEffects = true;
            this.settingBtn.AllowToggling = false;
            this.settingBtn.AnimationSpeed = 200;
            this.settingBtn.AutoGenerateColors = false;
            this.settingBtn.AutoRoundBorders = false;
            this.settingBtn.AutoSizeLeftIcon = true;
            this.settingBtn.AutoSizeRightIcon = true;
            this.settingBtn.BackColor = System.Drawing.Color.Transparent;
            this.settingBtn.BackColor1 = System.Drawing.Color.DarkTurquoise;
            this.settingBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("settingBtn.BackgroundImage")));
            this.settingBtn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.settingBtn.ButtonText = "Settting";
            this.settingBtn.ButtonTextMarginLeft = 0;
            this.settingBtn.ColorContrastOnClick = 45;
            this.settingBtn.ColorContrastOnHover = 45;
            this.settingBtn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.settingBtn.CustomizableEdges = borderEdges8;
            this.settingBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.settingBtn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.settingBtn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.settingBtn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.settingBtn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.settingBtn.Font = new System.Drawing.Font("Georgia", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.settingBtn.ForeColor = System.Drawing.Color.White;
            this.settingBtn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.settingBtn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.settingBtn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.settingBtn.IconMarginLeft = 11;
            this.settingBtn.IconPadding = 10;
            this.settingBtn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.settingBtn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.settingBtn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.settingBtn.IconSize = 25;
            this.settingBtn.IdleBorderColor = System.Drawing.Color.DarkTurquoise;
            this.settingBtn.IdleBorderRadius = 1;
            this.settingBtn.IdleBorderThickness = 1;
            this.settingBtn.IdleFillColor = System.Drawing.Color.DarkTurquoise;
            this.settingBtn.IdleIconLeftImage = null;
            this.settingBtn.IdleIconRightImage = null;
            this.settingBtn.IndicateFocus = false;
            this.settingBtn.Location = new System.Drawing.Point(84, 645);
            this.settingBtn.Margin = new System.Windows.Forms.Padding(4);
            this.settingBtn.Name = "settingBtn";
            this.settingBtn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.settingBtn.OnDisabledState.BorderRadius = 1;
            this.settingBtn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.settingBtn.OnDisabledState.BorderThickness = 1;
            this.settingBtn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.settingBtn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.settingBtn.OnDisabledState.IconLeftImage = null;
            this.settingBtn.OnDisabledState.IconRightImage = null;
            this.settingBtn.onHoverState.BorderColor = System.Drawing.Color.DarkTurquoise;
            this.settingBtn.onHoverState.BorderRadius = 1;
            this.settingBtn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.settingBtn.onHoverState.BorderThickness = 1;
            this.settingBtn.onHoverState.FillColor = System.Drawing.Color.LightSeaGreen;
            this.settingBtn.onHoverState.ForeColor = System.Drawing.Color.White;
            this.settingBtn.onHoverState.IconLeftImage = null;
            this.settingBtn.onHoverState.IconRightImage = null;
            this.settingBtn.OnIdleState.BorderColor = System.Drawing.Color.DarkTurquoise;
            this.settingBtn.OnIdleState.BorderRadius = 1;
            this.settingBtn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.settingBtn.OnIdleState.BorderThickness = 1;
            this.settingBtn.OnIdleState.FillColor = System.Drawing.Color.DarkTurquoise;
            this.settingBtn.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.settingBtn.OnIdleState.IconLeftImage = null;
            this.settingBtn.OnIdleState.IconRightImage = null;
            this.settingBtn.OnPressedState.BorderColor = System.Drawing.Color.DarkTurquoise;
            this.settingBtn.OnPressedState.BorderRadius = 1;
            this.settingBtn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.settingBtn.OnPressedState.BorderThickness = 1;
            this.settingBtn.OnPressedState.FillColor = System.Drawing.Color.LightSeaGreen;
            this.settingBtn.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.settingBtn.OnPressedState.IconLeftImage = null;
            this.settingBtn.OnPressedState.IconRightImage = null;
            this.settingBtn.Size = new System.Drawing.Size(114, 45);
            this.settingBtn.TabIndex = 7;
            this.settingBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.settingBtn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.settingBtn.TextMarginLeft = 0;
            this.settingBtn.TextPadding = new System.Windows.Forms.Padding(0);
            this.settingBtn.UseDefaultRadiusAndThickness = true;
            this.settingBtn.Click += new System.EventHandler(this.settingBtn_Click);
            // 
            // pictureBox1
            // 
            this.pictureBox1.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox1.Image")));
            this.pictureBox1.Location = new System.Drawing.Point(38, 115);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(137, 99);
            this.pictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox1.TabIndex = 11;
            this.pictureBox1.TabStop = false;
            // 
            // pictureBox2
            // 
            this.pictureBox2.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox2.Image")));
            this.pictureBox2.Location = new System.Drawing.Point(38, 241);
            this.pictureBox2.Name = "pictureBox2";
            this.pictureBox2.Size = new System.Drawing.Size(30, 30);
            this.pictureBox2.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox2.TabIndex = 12;
            this.pictureBox2.TabStop = false;
            // 
            // pictureBox3
            // 
            this.pictureBox3.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox3.Image")));
            this.pictureBox3.Location = new System.Drawing.Point(38, 301);
            this.pictureBox3.Name = "pictureBox3";
            this.pictureBox3.Size = new System.Drawing.Size(30, 30);
            this.pictureBox3.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox3.TabIndex = 13;
            this.pictureBox3.TabStop = false;
            // 
            // pictureBox4
            // 
            this.pictureBox4.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox4.Image")));
            this.pictureBox4.Location = new System.Drawing.Point(38, 361);
            this.pictureBox4.Name = "pictureBox4";
            this.pictureBox4.Size = new System.Drawing.Size(30, 30);
            this.pictureBox4.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox4.TabIndex = 14;
            this.pictureBox4.TabStop = false;
            // 
            // pictureBox5
            // 
            this.pictureBox5.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox5.Image")));
            this.pictureBox5.Location = new System.Drawing.Point(38, 421);
            this.pictureBox5.Name = "pictureBox5";
            this.pictureBox5.Size = new System.Drawing.Size(30, 30);
            this.pictureBox5.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox5.TabIndex = 15;
            this.pictureBox5.TabStop = false;
            // 
            // pictureBox6
            // 
            this.pictureBox6.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox6.Image")));
            this.pictureBox6.Location = new System.Drawing.Point(37, 537);
            this.pictureBox6.Name = "pictureBox6";
            this.pictureBox6.Size = new System.Drawing.Size(30, 30);
            this.pictureBox6.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox6.TabIndex = 16;
            this.pictureBox6.TabStop = false;
            // 
            // pictureBox7
            // 
            this.pictureBox7.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox7.Image")));
            this.pictureBox7.Location = new System.Drawing.Point(37, 597);
            this.pictureBox7.Name = "pictureBox7";
            this.pictureBox7.Size = new System.Drawing.Size(30, 30);
            this.pictureBox7.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox7.TabIndex = 17;
            this.pictureBox7.TabStop = false;
            // 
            // pictureBox8
            // 
            this.pictureBox8.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox8.Image")));
            this.pictureBox8.Location = new System.Drawing.Point(37, 657);
            this.pictureBox8.Name = "pictureBox8";
            this.pictureBox8.Size = new System.Drawing.Size(30, 30);
            this.pictureBox8.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox8.TabIndex = 18;
            this.pictureBox8.TabStop = false;
            // 
            // bunifuButton1
            // 
            this.bunifuButton1.AllowAnimations = true;
            this.bunifuButton1.AllowMouseEffects = true;
            this.bunifuButton1.AllowToggling = false;
            this.bunifuButton1.AnimationSpeed = 200;
            this.bunifuButton1.AutoGenerateColors = false;
            this.bunifuButton1.AutoRoundBorders = false;
            this.bunifuButton1.AutoSizeLeftIcon = true;
            this.bunifuButton1.AutoSizeRightIcon = true;
            this.bunifuButton1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton1.BackColor1 = System.Drawing.Color.DarkTurquoise;
            this.bunifuButton1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton1.BackgroundImage")));
            this.bunifuButton1.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.ButtonText = "Loan";
            this.bunifuButton1.ButtonTextMarginLeft = 0;
            this.bunifuButton1.ColorContrastOnClick = 45;
            this.bunifuButton1.ColorContrastOnHover = 45;
            this.bunifuButton1.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges9.BottomLeft = true;
            borderEdges9.BottomRight = true;
            borderEdges9.TopLeft = true;
            borderEdges9.TopRight = true;
            this.bunifuButton1.CustomizableEdges = borderEdges9;
            this.bunifuButton1.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton1.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton1.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton1.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton1.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton1.Font = new System.Drawing.Font("Georgia", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButton1.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton1.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton1.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton1.IconMarginLeft = 11;
            this.bunifuButton1.IconPadding = 10;
            this.bunifuButton1.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton1.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton1.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton1.IconSize = 25;
            this.bunifuButton1.IdleBorderColor = System.Drawing.Color.DarkTurquoise;
            this.bunifuButton1.IdleBorderRadius = 1;
            this.bunifuButton1.IdleBorderThickness = 1;
            this.bunifuButton1.IdleFillColor = System.Drawing.Color.DarkTurquoise;
            this.bunifuButton1.IdleIconLeftImage = null;
            this.bunifuButton1.IdleIconRightImage = null;
            this.bunifuButton1.IndicateFocus = false;
            this.bunifuButton1.Location = new System.Drawing.Point(86, 468);
            this.bunifuButton1.Margin = new System.Windows.Forms.Padding(4);
            this.bunifuButton1.Name = "bunifuButton1";
            this.bunifuButton1.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton1.OnDisabledState.BorderRadius = 1;
            this.bunifuButton1.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnDisabledState.BorderThickness = 1;
            this.bunifuButton1.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton1.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton1.OnDisabledState.IconLeftImage = null;
            this.bunifuButton1.OnDisabledState.IconRightImage = null;
            this.bunifuButton1.onHoverState.BorderColor = System.Drawing.Color.DarkTurquoise;
            this.bunifuButton1.onHoverState.BorderRadius = 1;
            this.bunifuButton1.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.onHoverState.BorderThickness = 1;
            this.bunifuButton1.onHoverState.FillColor = System.Drawing.Color.LightSeaGreen;
            this.bunifuButton1.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.onHoverState.IconLeftImage = null;
            this.bunifuButton1.onHoverState.IconRightImage = null;
            this.bunifuButton1.OnIdleState.BorderColor = System.Drawing.Color.DarkTurquoise;
            this.bunifuButton1.OnIdleState.BorderRadius = 1;
            this.bunifuButton1.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnIdleState.BorderThickness = 1;
            this.bunifuButton1.OnIdleState.FillColor = System.Drawing.Color.DarkTurquoise;
            this.bunifuButton1.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.OnIdleState.IconLeftImage = null;
            this.bunifuButton1.OnIdleState.IconRightImage = null;
            this.bunifuButton1.OnPressedState.BorderColor = System.Drawing.Color.DarkTurquoise;
            this.bunifuButton1.OnPressedState.BorderRadius = 1;
            this.bunifuButton1.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnPressedState.BorderThickness = 1;
            this.bunifuButton1.OnPressedState.FillColor = System.Drawing.Color.LightSeaGreen;
            this.bunifuButton1.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.OnPressedState.IconLeftImage = null;
            this.bunifuButton1.OnPressedState.IconRightImage = null;
            this.bunifuButton1.Size = new System.Drawing.Size(114, 45);
            this.bunifuButton1.TabIndex = 4;
            this.bunifuButton1.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton1.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton1.TextMarginLeft = 0;
            this.bunifuButton1.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton1.UseDefaultRadiusAndThickness = true;
            this.bunifuButton1.Click += new System.EventHandler(this.bunifuButton1_Click);
            // 
            // pictureBox9
            // 
            this.pictureBox9.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox9.Image")));
            this.pictureBox9.Location = new System.Drawing.Point(38, 476);
            this.pictureBox9.Name = "pictureBox9";
            this.pictureBox9.Size = new System.Drawing.Size(30, 30);
            this.pictureBox9.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox9.TabIndex = 20;
            this.pictureBox9.TabStop = false;
            // 
            // Main
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("$this.BackgroundImage")));
            this.ClientSize = new System.Drawing.Size(1366, 768);
            this.Controls.Add(this.pictureBox9);
            this.Controls.Add(this.bunifuButton1);
            this.Controls.Add(this.pictureBox8);
            this.Controls.Add(this.pictureBox7);
            this.Controls.Add(this.pictureBox6);
            this.Controls.Add(this.pictureBox5);
            this.Controls.Add(this.pictureBox4);
            this.Controls.Add(this.pictureBox3);
            this.Controls.Add(this.pictureBox2);
            this.Controls.Add(this.pictureBox1);
            this.Controls.Add(this.exitBtn);
            this.Controls.Add(this.settingBtn);
            this.Controls.Add(this.reportBtn);
            this.Controls.Add(this.branchBtn);
            this.Controls.Add(this.AttendenceBtn);
            this.Controls.Add(this.salaryBtn);
            this.Controls.Add(this.EmployeeBtn);
            this.Controls.Add(this.homeBtn);
            this.Controls.Add(this.panelContainer);
            this.Controls.Add(this.bunifuPanel1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "Main";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Main";
            this.WindowState = System.Windows.Forms.FormWindowState.Maximized;
            this.bunifuPanel1.ResumeLayout(false);
            this.bunifuPanel1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox3)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox4)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox5)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox6)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox7)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox8)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox9)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
        private Bunifu.UI.WinForms.BunifuPanel panelContainer;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton homeBtn;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
        private Bunifu.UI.WinForms.BunifuPictureBox bunifuPictureBox1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton EmployeeBtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton salaryBtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton AttendenceBtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton branchBtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton exitBtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton reportBtn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton settingBtn;
        private System.Windows.Forms.PictureBox pictureBox1;
        private System.Windows.Forms.PictureBox pictureBox2;
        private System.Windows.Forms.PictureBox pictureBox3;
        private System.Windows.Forms.PictureBox pictureBox4;
        private System.Windows.Forms.PictureBox pictureBox5;
        private System.Windows.Forms.PictureBox pictureBox6;
        private System.Windows.Forms.PictureBox pictureBox7;
        private System.Windows.Forms.PictureBox pictureBox8;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton1;
        private System.Windows.Forms.PictureBox pictureBox9;
    }
}